In [1]:
import numpy

# Forecasting number of available workers
D = numpy.array([[15,0,0],[0,20,0],[0,0,50]])
M = numpy.array([[5,2,0],[0,10,0],[5,5,45]])
b = numpy.array([[3],[0],[0]])
a = M@numpy.linalg.inv(D)@b
print(a)

# Forecasting demand for workers
X = numpy.array([[15,1,0,0],[17,1,0,0],[14,1,0,0],[6,0,1,0],[6,0,1,0],[5,0,1,0],[23,0,0,1],[27,0,0,1],[25,0,0,1]])
Y = numpy.array([[4],[6],[5],[13],[12],[13],[7],[7],[9]])
XTX = numpy.matmul(X.T,X)
print(XTX)
inverse = numpy.linalg.inv(XTX)
print(inverse)
XTY = numpy.matmul(X.T,Y)
print(XTY)
betas = numpy.matmul(inverse,XTY)
print(betas)

[[1.]
 [0.]
 [1.]]
[[2690   46   17   75]
 [  46    3    0    0]
 [  17    0    3    0]
 [  75    0    0    3]]
[[ 0.075      -1.15       -0.425      -1.875     ]
 [-1.15       17.96666667  6.51666667 28.75      ]
 [-0.425       6.51666667  2.74166667 10.625     ]
 [-1.875      28.75       10.625      47.20833333]]
[[1022]
 [  15]
 [  38]
 [  23]]
[[ 0.125     ]
 [ 3.08333333]
 [11.95833333]
 [ 4.54166667]]
